config/routes.rb
Rails.application.routes.draw do
  resources :whitewater_runs

  root 'whitewater_runs#index'

end

app/models/whitewater_run.rb
class WhitewaterRun < ActiveRecord::Base
    validates :name, :description, :whitewater_class, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/whitewater_runs_controller.rb
class WhitewaterRunsController < ApplicationController
  before_action :set_whitewater_run, only: [:show, :edit, :update, :destroy]

  # GET /whitewater_runs
  # GET /whitewater_runs.json
  def index
    @whitewater_runs = WhitewaterRun.all
  end

  # GET /whitewater_runs/1
  # GET /whitewater_runs/1.json
  def show
  end

  # GET /whitewater_runs/new
  def new
    @whitewater_run = WhitewaterRun.new
  end

  # GET /whitewater_runs/1/edit
  def edit
  end

  # POST /whitewater_runs
  # POST /whitewater_runs.json
  def create
    @whitewater_run = WhitewaterRun.new(whitewater_run_params)

    respond_to do |format|
      if @whitewater_run.save
        format.html { redirect_to @whitewater_run, notice: 'Whitewater run was successfully created.' }
        format.json { render :show, status: :created, location: @whitewater_run }
      else
        format.html { render :new }
        format.json { render json: @whitewater_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /whitewater_runs/1
  # PATCH/PUT /whitewater_runs/1.json
  def update
    respond_to do |format|
      if @whitewater_run.update(whitewater_run_params)
        format.html { redirect_to @whitewater_run, notice: 'Whitewater run was successfully updated.' }
        format.json { render :show, status: :ok, location: @whitewater_run }
      else
        format.html { render :edit }
        format.json { render json: @whitewater_run.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /whitewater_runs/1
  # DELETE /whitewater_runs/1.json
  def destroy
    @whitewater_run.destroy
    respond_to do |format|
      format.html { redirect_to whitewater_runs_url, notice: 'Whitewater run was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_whitewater_run
      @whitewater_run = WhitewaterRun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def whitewater_run_params
      params.require(:whitewater_run).permit(:description, :name, :whitewater_class)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/whitewater_runs_helper.rb
module WhitewaterRunsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhereIsTheWater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "shared/navbar" %>
<div class='app-body'>
<%= yield %>
</div>
</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Where Is the Water?</a>
  </div>
</div><!-- /.container-fluid -->
</nav>

app/views/whitewater_runs/_form.html.erb
<%= form_for(@whitewater_run) do |f| %>
    <form>
      <% if @whitewater_run.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@whitewater_run.errors.count, "error") %> need to be fixed before this can be saved:</h2>

          <ul>
          <% @whitewater_run.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field form-group">
        <%= f.label :whitewater_class %><br>
        <%= f.number_field :whitewater_class %>
      </div>
      <div class="field form-group">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <button type="button" class="btn btn-default">
        <%= f.submit %>
      </div>
  </form>
<% end %>

app/views/whitewater_runs/edit.html.erb
<h1>Editing Whitewater Run</h1>

<%= render 'form' %>

<%= link_to 'Show', @whitewater_run %> |
<%= link_to 'Back', whitewater_runs_path %>

app/views/whitewater_runs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Whitewater Runs</h1>

<div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Whitewater class</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @whitewater_runs.each do |whitewater_run| %>
          <tr>
            <td><%= whitewater_run.name %></td>
            <td><%= whitewater_run.whitewater_class %></td>
            <td><%= whitewater_run.description %></td>
            <td><%= link_to 'Show', whitewater_run %></td>
            <td><%= link_to 'Edit', edit_whitewater_run_path(whitewater_run) %></td>
            <td><%= link_to 'Destroy', whitewater_run, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<br>

<%= link_to 'New Whitewater run', new_whitewater_run_path %>

app/views/whitewater_runs/new.html.erb
<h1>New Whitewater Run</h1>

<%= render 'form' %>

<%= link_to 'Back', whitewater_runs_path %>

app/views/whitewater_runs/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @whitewater_run.name %>
</p>

<p>
  <strong>Whitewater class:</strong>
  <%= @whitewater_run.whitewater_class %>
</p>

<p>
  <strong>Description:</strong>
  <%= @whitewater_run.description %>
</p>

<%= link_to 'Edit', edit_whitewater_run_path(@whitewater_run) %> |
<%= link_to 'Back', whitewater_runs_path %>